### ISSUE TITLE
We need a t-shirt design

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe-graphics#2]
I will be presenting at FOSSASIA on InaSAFE and would like to wear a tshirt during the presentation to promote InaSAFE. I was thinking of a simple design with the InaSAFE logo, the word InaSAFE above it and the words "Prepare, Persist" below it. @Charlotte-Morgan comments welcome.

**Comment by MariaSolovyeva** [comment]
Hi @timlinux , I need some details:

- the t-shirt color
- the image size (full front, left chest, etc..)

Thanks!

**Comment by MariaSolovyeva** [comment]
Hi @timlinux , I need some details:
- the t-shirt color
- the image size (full front, left chest, etc..)

Thanks!

**Comment by timlinux** [comment]
Hi

So:
- front of tshirt
- large, so it is visible from far away
- white or black - you tell us which is going to work best

For the design:

```
InaSAFE logo with URL

"Better planning saves lives"
```

Or similar - use your initiative to come up with something if you have a nicer idea, we just need to include the key elements:

Logo
URL
InaSAFE
"Better planning saves lives"

Thanks @MariaSolovyeva

**Comment by MariaSolovyeva** [comment]
Hello @timlinux , here are few variants of t-shirt design, let me know!

![t-shirt1](https://cloud.githubusercontent.com/assets/10400420/6571533/710d49ac-c71a-11e4-84ce-fad9c1202edb.jpg)
![t-shirt1-dark](https://cloud.githubusercontent.com/assets/10400420/6571535/711030a4-c71a-11e4-8e53-9494f43726cc.jpg)
![t-shirt2](https://cloud.githubusercontent.com/assets/10400420/6571534/71100246-c71a-11e4-8d0f-a97a6dee9da8.jpg)
![t-shirt2-dark](https://cloud.githubusercontent.com/assets/10400420/6571536/71108720-c71a-11e4-89b7-5a1290ed8c2c.jpg)

**Comment by MariaSolovyeva** [comment]
![t-shirt2-grey](https://cloud.githubusercontent.com/assets/10400420/6580126/764b1eb8-c75f-11e4-88ea-4b345d2e93d2.jpg)
![t-shirt2-lightgrey](https://cloud.githubusercontent.com/assets/10400420/6580127/764ed8dc-c75f-11e4-8f15-fe8a14de9c9d.jpg)
![t-shirt2-orange](https://cloud.githubusercontent.com/assets/10400420/6580125/75ec095a-c75f-11e4-87fe-971e5fceecb9.jpg)

**Comment by mach0** [comment]
I'm deeply impressed, very nice designs!

**Comment by timlinux** [comment]
glad you like it @mach0

**Comment by MariaSolovyeva** [comment]
thank you @mach0 !
